openapi: 3.0.0
info:
  title: Proyecto ODS API
  description: API para gestionar las iniciativas, trabajadores, cursos y más en el contexto del Proyecto ODS.
  version: 1.0.0
paths:
  /iniciativas:
    get:
      summary: Obtener todas las iniciativas
      responses:
        '200':
          description: Lista de iniciativas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    CODINICIATIVA:
                      type: integer
                    ACCION:
                      type: string
                    HORAS:
                      type: integer
                    NOMBRE:
                      type: string
                    PRODUCTOFINAL:
                      type: string
                    FECHAINICIO:
                      type: string
                      format: date-time
                    FECHAFIN:
                      type: string
                      format: date-time
                    CODIGOENTIDADES:
                      type: integer
                    IDTRABAJADOR:
                      type: integer
    post:
      summary: Crear una nueva iniciativa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ACCION:
                  type: string
                HORAS:
                  type: integer
                NOMBRE:
                  type: string
                PRODUCTOFINAL:
                  type: string
                FECHAINICIO:
                  type: string
                  format: date-time
                FECHAFIN:
                  type: string
                  format: date-time
                CODIGOENTIDADES:
                  type: integer
                IDTRABAJADOR:
                  type: integer
      responses:
        '201':
          description: Iniciativa creada con éxito
  /trabajadores:
    get:
      summary: Obtener todos los trabajadores
      responses:
        '200':
          description: Lista de trabajadores
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    IDTRABAJADOR:
                      type: integer
                    NOMBRE:
                      type: string
    post:
      summary: Crear un nuevo trabajador
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                NOMBRE:
                  type: string
      responses:
        '201':
          description: Trabajador creado con éxito
  /cursos:
    get:
      summary: Obtener todos los cursos
      responses:
        '200':
          description: Lista de cursos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    CODIGOCURSO:
                      type: integer
                    NOMBRE:
                      type: string
    post:
      summary: Crear un nuevo curso
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                NOMBRE:
                  type: string
      responses:
        '201':
          description: Curso creado con éxito
  /entidades:
    get:
      summary: Obtener todas las entidades externas
      responses:
        '200':
          description: Lista de entidades externas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    CODIGOENTIDADES:
                      type: integer
                    NOMBREENTIDADEXT:
                      type: string
    post:
      summary: Crear una nueva entidad externa
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                NOMBREENTIDADEXT:
                  type: string
      responses:
        '201':
          description: Entidad externa creada con éxito
  /metas:
    get:
      summary: Obtener todas las metas
      responses:
        '200':
          description: Lista de metas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ods:
                      type: integer
                    CODIGOMETAS:
                      type: string
                    DESCRIPCION:
                      type: string
    post:
      summary: Crear una nueva meta
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                ods:
                  type: integer
                CODIGOMETAS:
                  type: string
                DESCRIPCION:
                  type: string
      responses:
        '201':
          description: Meta creada con éxito
  /ods:
    get:
      summary: Obtener todas las dimensiones ODS
      responses:
        '200':
          description: Lista de dimensiones ODS
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    ods:
                      type: integer
                    NOMBRE:
                      type: string
                    DIMENSIÓN:
                      type: string
    post:
      summary: Crear una nueva dimensión ODS
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                NOMBRE:
                  type: string
                DIMENSIÓN:
                  type: string
      responses:
        '201':
          description: Dimensión ODS creada con éxito
components:
  schemas:
    Iniciativa:
      type: object
      properties:
        CODINICIATIVA:
          type: integer
        ACCION:
          type: string
        HORAS:
          type: integer
        NOMBRE:
          type: string
        PRODUCTOFINAL:
          type: string
        FECHAINICIO:
          type: string
          format: date-time
        FECHAFIN:
          type: string
          format: date-time
        CODIGOENTIDADES:
          type: integer
        IDTRABAJADOR:
          type: integer
    Trabajador:
      type: object
      properties:
        IDTRABAJADOR:
          type: integer
        NOMBRE:
          type: string
    Curso:
      type: object
      properties:
        CODIGOCURSO:
          type: integer
        NOMBRE:
          type: string
    Meta:
      type: object
      properties:
        ods:
          type: integer
        CODIGOMETAS:
          type: string
        DESCRIPCION:
          type: string
    ODS:
      type: object
      properties:
        ods:
          type: integer
        NOMBRE:
          type: string
        DIMENSIÓN:
          type: string
    EntidadExterna:
      type: object
      properties:
        CODIGOENTIDADES:
          type: integer
        NOMBREENTIDADEXT:
          type: string
